dist: xenial
sudo: false
branches:
  except:
  - gh-pages
language: ruby
cache:
  - bundler
before_install:
  - gem update --system
  - gem install bundler
install:
  - pip install --user $(whoami) --upgrade ghp-import
  - bundle install --jobs=3
script:
  - bundle exec jekyll build
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
