dist: xenial
sudo: false
branches:
  except:
  - gh-pages
language: ruby
before_install:
  - which python
  - python --version
  - gem update --system
  - gem install bundler
install:
  - bundle install
script:
  - bundle exec jekyll build
deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
 