name: Build manubot.org
on:
  push:
  pull_request:
  repository_dispatch:
    types:
      - catalog-update
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'
      - name: Install dependencies
        run: |
          gem install bundler --version=2.3.26
          bundle install --jobs=3
      - name: Build website
        run: bundle exec jekyll build
      - name: Deploy website
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && !github.event.repository.fork
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          cname: manubot.org
