name: Build manubot.org
on:
  push:
  pull_request:
  schedule:
    # At 03:45 on Saturday https://crontab.guru/#45_3_*_*_6
    # One hour after manubot/catalog cron job.
    - cron: "45 3 * * 6"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs=3
      - name: Build website
        run: bundle exec jekyll build
      - name: Deploy website
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && !github.event.repository.fork
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          cname: manubot.org
